# Site
repository: Jinniepoo/Jinniepoo.github.io
# favicon: images/favicon.ico  # 원하면 파비콘 경로 추가

# Content configuration version
version: 2

# Personal info
name: An Yoo Jin
title: Client Programmer
email: j.ambitious97@gmail.com
website: https://github.com/Jinniepoo

# Dark Mode (true/false/never)
darkmode: true

# Social links (필요한 것만 수정해서 쓰면 됨)
github_username:  Jinniepoo
linkedin_username: jekyll  # 수정 필요
twitter_username: jekyllrb

# Additional icon links
additional_links:
- title: Portfolio
  icon: fas fa-globe
  url: https://github.com/Jinniepoo

# About Section
about_profile_image: images/profile.jpg
about_content: | 
  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

  You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
    - Lists
    - Tables
    - <a href="google.com">Links</a>
    - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        border: weak
        title: Project name
        link: https://github.com/Jinniepoo
        link_text: GitHub Repo
        additional_links:
          - title: Github
            icon: fab fa-github
            url: https://github.com/Jinniepoo
        quote: >
          Short overview of the project
        description: |
          Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Company name
        sub_title: Job title
        caption: Date Range
        link: 
        quote: >
          Short description of the company
        description: |
          Description of role
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Institution name
        sub_title: Qualifications
        caption: Date Range
        quote: >
          Short institution or course description
        description: |
          Description of qualification
  - title: A Little More About Me
    layout: text
    content: |
      This is where you can write a little more about yourself. 
      You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request

# Build settings
remote_theme: sproogen/modern-resume-theme

plugins:
 - jekyll-seo-tag
 - jekyll-remote-theme

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
